# Generated by Django 5.0.1 on 2024-01-24 13:22

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CARD', 'Карта'), ('ACCOUNT', 'Платежный счет')], max_length=7, verbose_name='Тип платежа')),
                ('card_or_account_type', models.CharField(max_length=30, verbose_name='Тип карты/счета')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО владельца')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Лимит')),
            ],
            options={
                'verbose_name': 'Реквизит',
                'verbose_name_plural': 'Реквизиты',
                'db_table': 'requisites',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='Сумма заявки')),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Ожидает оплаты'), ('PAID', 'Оплачена'), ('CANCELED', 'Отменена')], max_length=16, verbose_name='Статус заявки')),
                ('requisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.requisite', verbose_name='Реквизиты заявки')),
            ],
            options={
                'verbose_name': 'Заявка на оплату',
                'verbose_name_plural': 'Заявки на оплату',
                'db_table': 'invoices',
            },
        ),
    ]
